services:
  postgres:
    image: postgres:17
    ports: 
      - "$PG_PORT:5432"
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DBNAME
    volumes:
      - pg-data:/var/lib/pg/data
  
  minio:
    image: minio/minio
    command: server /var/lib/minio/data --console-address ":9001"
    ports:
      - "$MINIO_API_PORT:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/var/lib/minio/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '$PROM_PORT:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://localhost:9090'

  backend:
    image: randomrandoms/picstore-back
    command: cargo run --release
    ports: 
      - "$BACKEND_PORT:3000"
    depends_on:
      - postgres
      - minio
      - prometheus
    environment:
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_HOST: postgres
      PG_DBNAME: $PG_DBNAME
      RUST_LOG: info
      PG_PORT: $PG_PORT
      MINIO_API_PORT: $MINIO_API_PORT

volumes:
  pg-data:
  minio-data:

networks:
  web:
    driver: bridge
